const data = [
  {
    item_name: "Item name is this long for example",
    manufacturer: "Manufactured Name",
    notes: "Notes",
    unit: "Unit here",
    category: "Gym Equipment",
    model: " Model#",
    group: "groupe here",
    tagss: "tags here",
    image_upload:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSS979zr3oEyc5o5Af0RZ-dmcqPUiJ_UMhp4A&usqp=CAU",
    link: "LInk here",
    status: "active",
    company_name: "NASA",
    userId: "8d5d5fd",
  },
  {
    item_name: "Item name is this long for example",
    manufacturer: "Manufactured Name",
    notes: "Notes",
    unit: "Unit here",
    category: "Gym Equipment",
    model: " Model#",
    group: "groupe here",
    tagss: "tags here",
    image_upload:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSS979zr3oEyc5o5Af0RZ-dmcqPUiJ_UMhp4A&usqp=CAU",
    link: "LInk here",
    status: "active",
    company_name: "NASA",
    userId: "d8s8sdf",
  },
  {
    item_name: "Item name is this long for example",
    manufacturer: "Manufactured Name",
    notes: "Notes",
    unit: "Unit here",
    category: "Gym Equipment",
    model: " Model#",
    group: "groupe here",
    tagss: "tags here",
    image_upload:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSS979zr3oEyc5o5Af0RZ-dmcqPUiJ_UMhp4A&usqp=CAU",
    link: "LInk here",
    status: "active",
    company_name: "NASA",
    userId: "8d7e8d",
  },
  {
    item_name: "Item name is this long for example",
    manufacturer: "Manufactured Name",
    notes: "Notes",
    unit: "Unit here",
    category: "Gym Equipment",
    model: " Model#",
    group: "groupe here",
    tagss: "tags here",
    image_upload:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSS979zr3oEyc5o5Af0RZ-dmcqPUiJ_UMhp4A&usqp=CAU",
    link: "LInk here",
    status: "active",
    company_name: "NASA",
    userId: "9w34ssd",
  },
  {
    item_name: "Item name is this long for example",
    manufacturer: "Manufactured Name",
    notes: "Notes",
    unit: "Unit here",
    category: "Gym Equipment",
    model: " Model#",
    group: "groupe here",
    tagss: "tags here",
    image_upload:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSS979zr3oEyc5o5Af0RZ-dmcqPUiJ_UMhp4A&usqp=CAU",
    link: "LInk here",
    status: "active",
    company_name: "NASA",
    userId: "25blos",
  },
  {
    item_name: "Item name is this long for example",
    manufacturer: "Manufactured Name",
    notes: "Notes",
    unit: "Unit here",
    category: "Gym Equipment",
    model: " Model#",
    group: "groupe here",
    tagss: "tags here",
    image_upload:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSS979zr3oEyc5o5Af0RZ-dmcqPUiJ_UMhp4A&usqp=CAU",
    link: "LInk here",
    status: "active",
    company_name: "NASA",
    userId: "7883s98df",
  },
];

export default data;
